//
// Created by Nataf on 02/06/2020.
//

#ifndef SOFTWARE_VERIF_PROJECT_MASTER_ALLOC_MANAGER_H
#define SOFTWARE_VERIF_PROJECT_MASTER_ALLOC_MANAGER_H
void* xmalloc(size_t size);
#endif //SOFTWARE_VERIF_PROJECT_MASTER_ALLOC_MANAGER_H
